
name: Clean images

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # every day at midnight

jobs:
  clean-ghcr:
      name: Delete old unused container images
      runs-on: ubuntu-latest
      steps:
        - name: delete containers
          uses: snok/container-retention-policy@v1.5.1
          with:
            image-names: someapi-service,somebackgroundworker-service
            cut-off: 14 days ago UTC
            account-type: org
            org-name: AUTOProff
            keep-at-least: 3
            token: ${{ secrets.MY_PAT }}
