name: Release dev [DEV02]

on:
  push:
    tags:
      - main.**
  workflow_dispatch:

jobs:
  release-SomeAPi-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: dev
      prefix: dev
      cluster: autoproff-cluster
      service_name: SomeAPi-service
      branch_name: main
      

  release-SomeBackgroundWorker-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: dev
      prefix: dev
      cluster: autoproff-cluster
      service_name: SomeBackgroundWorker-service
      branch_name: main
      
