name: Release dev [DEV02]

on:
  push:
    tags:
      - dev.**
  workflow_dispatch:

jobs:
  release-SomeAPi-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: dev02
      prefix: dev
      cluster: autoproff-cluster
      service_name: SomeAPi-service
      dockerfile: "Dockerfile"
      branch_name: dev
      

  release-SomeBackgroundWorker-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: dev02
      prefix: dev
      cluster: autoproff-cluster
      service_name: SomeBackgroundWorker-service
      dockerfile: "Dockerfile"
      branch_name: dev
      
