name: Release QA [STAGE02]      

on:
  push:
    tags:
      - release.**
  workflow_dispatch:

jobs:
  release-SomeAPi-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: stage02
      prefix: stage
      cluster: autoproff-cluster
      service_name: SomeAPi-service
      dockerfile: "Dockerfile"
      branch_name: release
      

  release-SomeBackgroundWorker-service:
    secrets: inherit
    uses: ./.github/workflows/release-reuse.yml
    with:
      environment: stage02
      prefix: stage
      cluster: autoproff-cluster
      service_name: SomeBackgroundWorker-service
      dockerfile: "Dockerfile"
      branch_name: release
      
