
name: run sanity tests

on:
  workflow_run:
    workflows:
      - Release QA \[STAGE02\]
    types:
      - completed

jobs:
  sanity_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: main 
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build --no-restore --filter Category=SanityTest
